### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by albertborsos** [albertborsos/yii2-ddd#6]
- [x] call `MockTrait::mockObject()` to check compatibility in every php version 
 - [x] TBD

**Comment by ZhandosKz** [comment]
Hi! Where are your tests?

**Comment by albertborsos** [comment]
Hi @ZhandosKz! They are under development.

**Comment by ZhandosKz** [comment]
Thank you @albertborsos! I am waiting for it )

**Comment by ZhandosKz** [comment]
@albertborsos thank you!
